python src/response_prediction/run_seq2seq_rp.py \
    --model_name_or_path google/mt5-small \
    --do_train \
    --do_eval \
    --train_file data/rp/train.soloist.json \
    --validation_file data/rp/valid.soloist.json \
    --source_prefix "predict the response: " \
    --output_dir ./models/rp/ \
    --overwrite_output_dir \
    --per_device_train_batch_size=4 \
    --per_device_eval_batch_size=4 \
    --predict_with_generate \
    --save_strategy='epoch' \
    --evaluation_strategy='epoch' \
    --save_total_limit=1 \
    --load_best_model_at_end=True \
    --num_train_epochs=5 \
    --seed=1